### ISSUE TITLE
Directorate Members in Path 2

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-elegy/rfc8989bis#1]
Members of directorates have been vetted by leadership and (if the directorate is managed correctly) have been actively contributing reviews.

We could add "directorate member" to Path 2, maybe if they've been in good standing for 2 years.

**Comment by mcr** [comment]
This seems like a good thing to me.

**Comment by larseggert** [comment]
Do we mean directorates specifically, or also (some of) the other types of groups we have? See https://datatracker.ietf.org/group/

**Comment by martinduke** [comment]
I don't have a strong opinion about other groups, but to me the criteria are that they (1) do work and (2) their membership is vetted in some way (i.e. you can be fired for not doing anything)

**Comment by martinduke** [comment]
As discussed at the interim, I don't think this makes any sense given our full inclusion of remote participants. No one spoke up for this at the meeting so I'm closing it.
