### ISSUE TITLE
Inferior Working Group Functionaries

### ISSUE THREAD

**Issue by d3e3e3** [ietf-wg-elegy/rfc8989bis#10]
Working Group Chairs are substantially involved in IETF processes and are trusted to make consensus judgements. It is reasonable for someone who has served for a reasonable length of time as a Working Group Chair to be eligible to serve on the Nominations Committee, although it appears this will only enable a tiny number of people who would not otherwise qualify.

The same cannot be said of Working Group Secretaries or other Working Group functionaries, such as Technical Advisors or meeting scribes, who can be appointed and removed by the Chair. They should not, merely because they are such WG functionaries, be thereby eligible for Nominations Committee voting membership.

**Comment by martinduke** [comment]
Discussed in London. No one strongly objects to keeping secretaries in.
