### ISSUE TITLE
Attendance Criteria is Way Too Lax

### ISSUE THREAD

**Issue by d3e3e3** [ietf-wg-elegy/rfc8989bis#9]
While it is true that just picking up your badge counted as "attendance" in the past, in reality the vast majority of "attendees" at IETF meetings attended numerous sessions over several days if not the entire week. Since session attendance was recorded manually on the Blue Sheets, it would have been quite burdensome to actually check the number of sessions someone had attended, or the like.

Now, with hybrid meetings, per session attendance data is all available online. This makes it practical to require larger amount of participation at IETF meetings as part of the criteria for nomcom eligibility. The current criteria in the draft, of checking in to attend one session, is way too lax. A person who habitually attends only one session per IETF meeting or who only attends session of one WG is a very narrow participant in the IETF and should not be eligible for nomcom.

For an example of attendance criteria for a week long meeting that has been used by another standards organization, see Section 7.1 of https://mentor.ieee.org/802.11/dcn/14/11-14-0629-21-0000-802-11-operations-manual.docx which defines attendance as attending for 75% of the session hours during a week. (In 802.11, attendance is used to earn voting rights.) I do not think we need to be that stringent. But I would say that someone who does not attend at least two sessions a day for three days of an IETF meeting week really cannot be reasonably described as having attended that IETF meeting.

**Comment by mstjohns** [comment]
Yeah - no.   A good portion of the participation that's most useful for a Nomcom participant are the various ad-hoc hallway and bar sessions.   Now I'm not necessarily opposed to including my bar tab and a list of interactees when I volunteer for the Nomcom, but I think that might be difficult to verify and tabulate by a third party.    

WRT to the comparison to an IEEE meeting - I'm not very familiar with the scope of the meeting to which the 75% applies, but from discussions with folk who have attended IEEE as part of their funded lifestyles, that IEEE meeting you're referring to tends to be more closely matched in scope to an IETF working group or small cluster of working groups than to the IETF week-long whole ball of wax.  

I would oppose this change in criteria.  Mike

**Comment by martinduke** [comment]
The solution was to add some text to security consderations (see #12).

Leaving this open for now, but will close later if there are no further concerns.

**Comment by martinduke** [comment]
Closing due to a lack of additional comments.
